### PR TITLE
Updated game framework and visuals

### PR DESCRIPTION
**Pull request by SamGriffithsDev**

### CODE REVIEW

**Comment by SamGriffithsDev** [comment]
@troylusty This is ready to be merged whenever however my changes to 'Content/LevelDesign/BlockoutLevel2.umap' need to be removed. Would you be able to do this before accepting as I won't be at my computer until late Monday?

**Comment by troylusty** [comment]
> @troylusty This is ready to be merged whenever however my changes to 'Content/LevelDesign/BlockoutLevel2.umap' need to be removed. Would you be able to do this before accepting as I won't be at my computer until late Monday?

Yes of course that's fine. I'll do that now. However, are you able to suggest a new name for the merge commit that will better encompass all changes made within?

**Comment by troylusty** [comment]
Sorry for the amount of additional commits. It took me a while to realize I was taking the file from the wrong commit.

**Review by troylusty — APPROVED** [review]
Everything looks fine now.

**Pull request merged**
